"""
Source-text management for the question-bank pipeline.

Each event has a `texts/` directory holding reference material the LLM can
use to generate fresh questions:

    <event>/texts/
        wiki.md                  # scraped from scioly.org/wiki/<event>
        my_handout.pdf           # user-supplied PDF
        my_handout.md            # generated by pdf_to_markdown()

The pipeline tracks original-vs-derived via filename: <name>.pdf + <name>.md
"""

from __future__ import annotations

import re
from pathlib import Path

import fitz   # PyMuPDF
import requests

import pdf_safety
from events import Event


# ---------------------------------------------------------------------------
# Directory helpers
# ---------------------------------------------------------------------------

def texts_dir(event: Event) -> Path:
    d = event.texts_dir
    d.mkdir(exist_ok=True)
    return d


def list_sources(event: Event) -> list[dict]:
    """Return one entry per source file in the event's texts/ directory.
    A PDF + its sibling .md count as a single PDF entry (markdown shown as
    metadata). Standalone .md / .txt files are their own entries."""
    d = texts_dir(event)
    files = [f for f in d.iterdir()
             if f.is_file() and f.suffix.lower() in (".pdf", ".md", ".txt")]
    pdf_stems = {f.stem for f in files if f.suffix.lower() == ".pdf"}

    out: list[dict] = []
    for f in sorted(files, key=lambda p: p.name.lower()):
        suffix = f.suffix.lower()
        stem = f.stem
        if suffix == ".pdf":
            md = f.with_suffix(".md")
            out.append({
                "name": f.name, "stem": stem, "kind": "pdf",
                "size": f.stat().st_size,
                "has_markdown": md.exists(),
                "markdown_name": md.name if md.exists() else None,
                "markdown_size": md.stat().st_size if md.exists() else 0,
            })
        elif stem not in pdf_stems:
            # Standalone .md / .txt (no sibling PDF)
            out.append({
                "name": f.name, "stem": stem,
                "kind": suffix.lstrip("."),
                "size": f.stat().st_size,
                "has_markdown": True,
                "markdown_name": f.name,
                "markdown_size": f.stat().st_size,
            })
    return out


# ---------------------------------------------------------------------------
# Wiki scraping
# ---------------------------------------------------------------------------

_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
)


def scrape_wiki(event: Event, cookies: list[dict] | None = None) -> Path:
    """
    Fetch the scioly.org wiki page for `event`, convert to markdown,
    save as <event>/texts/wiki.md, return the path.
    """
    from bs4 import BeautifulSoup
    from markdownify import markdownify

    sess = requests.Session()
    sess.headers.update({
        "User-Agent": _UA,
        "Accept": "text/html,*/*",
        "Referer": "https://scioly.org/wiki/",
    })
    if cookies:
        for c in cookies:
            try:
                sess.cookies.set(c["name"], c["value"],
                                 domain=c.get("domain") or "scioly.org",
                                 path=c.get("path", "/"))
            except Exception:
                pass

    url = event.wiki_url
    r = sess.get(url, timeout=30)
    ctype = r.headers.get("content-type", "")
    if "not a bot" in r.text[:600].lower() or "anubis" in r.text[:600].lower():
        raise RuntimeError(
            "Anubis bot challenge — your cookies are missing or incomplete. "
            "Pasting just `document.cookie` from the browser console won't "
            "work: scioly.org's real session cookies (scioly_sid/scioly_k/"
            "scioly_u) are httpOnly and invisible to document.cookie. Open "
            "DevTools → Application/Storage → Cookies → scioly.org and copy "
            "every cookie listed there (not just the techaro.lol-anubis-* "
            "ones), or run `python download_event.py --event "
            f"{event.slug} --reauth` to refresh cookies, then retry."
        )
    if r.status_code != 200:
        raise RuntimeError(f"HTTP {r.status_code} fetching {url}")

    soup = BeautifulSoup(r.text, "html.parser")
    content = (soup.find("div", class_="mw-parser-output")
               or soup.find(id="mw-content-text")
               or soup.body)
    if content is None:
        raise RuntimeError("Could not find article content in wiki HTML")

    # Strip MediaWiki noise that doesn't translate well
    for tag in content.find_all(["span", "div"],
                                class_=lambda c: c and (
                                    "mw-editsection" in c
                                    or "noprint" in c
                                    or "toc" in c
                                )):
        tag.decompose()
    for sel in ("table.metadata", "#toc", ".printfooter",
                ".mw-jump-link", ".navbox"):
        for t in content.select(sel):
            t.decompose()

    md = markdownify(str(content), heading_style="ATX", bullets="-")
    md = re.sub(r"\n{3,}", "\n\n", md).strip()

    header = (
        f"# {event.name} — Wiki\n\n"
        f"*Source: {url}*  \n*Length: {len(md)} chars*\n\n---\n\n"
    )
    out = texts_dir(event) / "wiki.md"
    out.write_text(header + md, encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# PDF → markdown
# ---------------------------------------------------------------------------

def pdf_to_markdown(pdf_path: Path) -> Path:
    """
    Extract text from a PDF and save as a sibling .md file.
    Simple page-by-page text dump — preserves structure better than nothing,
    keeps the file readable for LLM ingestion.
    """
    if not pdf_path.exists():
        raise FileNotFoundError(pdf_path)
    if pdf_path.suffix.lower() != ".pdf":
        raise ValueError("not a PDF")

    doc = pdf_safety.open_pdf_safely(pdf_path)
    parts: list[str] = [f"# {pdf_path.stem}\n",
                        f"*Source: {pdf_path.name}, {doc.page_count} pages*\n", "---\n"]
    for pno, page in enumerate(doc, 1):
        text = page.get_text("text").strip()
        if not text:
            continue
        text = re.sub(r"[ \t]+\n", "\n", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        parts.append(f"\n## Page {pno}\n\n{text}\n")
    doc.close()

    out = pdf_path.with_suffix(".md")
    out.write_text("\n".join(parts), encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# Textbook chapter detection
# ---------------------------------------------------------------------------

# "Chapter 3", "CHAPTER ONE", "Unit IV", "Section 2:" — a heading line, not a
# mid-sentence mention, so this only matches at the START of a (stripped) line.
_CHAPTER_RE = re.compile(
    r"^(?:chapter|unit|section)\s+([0-9]{1,3}|[ivxlcdm]{1,7}|[a-z]+)\b[:.\-—]?\s*(.*)$",
    re.IGNORECASE,
)
# pdf_to_markdown() tags every page with exactly this marker (see above).
_PAGE_MARKER_RE = re.compile(r"^##\s*Page\s+(\d+)\s*$")


def detect_chapters(pdf_path: Path, md_text: str) -> dict:
    """
    Find chapter boundaries for a shared textbook PDF, for the "generate
    questions from one chapter" feature. Two strategies, tried in order:

    1. The PDF's own embedded outline/bookmarks (`get_toc()`) — exact page
       numbers, used as-is when present.
    2. A regex scan of `md_text` (the page-tagged dump `pdf_to_markdown()`
       produces) for "Chapter N" / "Unit N" / "Section N" style heading
       lines, tracking the most recent `## Page N` marker to assign each
       match's starting page. Needed because most textbook PDFs have no
       embedded bookmarks at all.

    If neither finds anything, the caller should fall back to letting the
    user type in chapter boundaries by hand.

    Returns {"chapters": [{"title","start_page","end_page"}, ...],
             "source": "toc"|"text-scan"|"manual", "needs_manual_chapters": bool}
    """
    raw: list[tuple[str, int]] = []  # (title, start_page)
    last_page = 0

    try:
        doc = pdf_safety.open_pdf_safely(pdf_path)
        toc = doc.get_toc()  # [[level, title, page], ...]
        last_page = doc.page_count
        doc.close()
    except Exception:
        toc = []

    if toc:
        top_level = min(lvl for lvl, _, _ in toc)
        raw = [(title.strip(), page) for lvl, title, page in toc if lvl == top_level]
        source = "toc"
    else:
        cur_page = 1
        for line in md_text.splitlines():
            stripped = line.strip()
            pm = _PAGE_MARKER_RE.match(stripped)
            if pm:
                cur_page = int(pm.group(1))
                last_page = max(last_page, cur_page)
                continue
            if _CHAPTER_RE.match(stripped):
                raw.append((stripped, cur_page))
        source = "text-scan"

    if not raw:
        return {"chapters": [], "source": "manual", "needs_manual_chapters": True}

    chapters = []
    for i, (title, start) in enumerate(raw):
        end = raw[i + 1][1] - 1 if i + 1 < len(raw) else max(last_page, start)
        chapters.append({"title": title, "start_page": start,
                          "end_page": max(end, start)})
    return {"chapters": chapters, "source": source, "needs_manual_chapters": False}


def read_source_text(event: Event, name: str) -> str:
    """
    Load the markdown form of a source by its base name.
    - "wiki.md" -> read wiki.md
    - "foo.pdf" -> read foo.md (PDF must have been processed first)
    - "foo.md"  -> read foo.md
    """
    d = texts_dir(event)
    p = d / name
    if name.lower().endswith(".pdf"):
        p = d / (Path(name).stem + ".md")
        if not p.exists():
            raise FileNotFoundError(
                f"{name} has not been converted to markdown yet — process it first.")
    if not p.exists():
        raise FileNotFoundError(p)
    return p.read_text(encoding="utf-8")
