#!/usr/bin/env bash
# Copies each event's extracted question data into a private GitHub "databank"
# repo clone and commits, with a human-readable commit message generated by
# qbank-commit-message.py. Safe to run often (every 1-4 hours via cron) —
# unlike deploying code, backing up data more frequently is strictly safer.
#
#   deploy/backup-extracted-data.sh <instance-app-dir> <databank-clone-dir> <backup-env-file>
#
# Example: deploy/backup-extracted-data.sh /opt/qbank/app /opt/qbank/databank /opt/qbank/backup/.env

set -euo pipefail

APP_DIR="${1:?usage: backup-extracted-data.sh <instance-app-dir> <databank-clone-dir> <backup-env-file>}"
DATABANK_DIR="${2:?usage: backup-extracted-data.sh <instance-app-dir> <databank-clone-dir> <backup-env-file>}"
ENV_FILE="${3:?usage: backup-extracted-data.sh <instance-app-dir> <databank-clone-dir> <backup-env-file>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

set -a
source "$ENV_FILE"
set +a

# Discover events dynamically — any top-level directory with a
# .qbank_state.json is an event, no hardcoded list to maintain.
EVENTS=()
for f in "$APP_DIR"/*/.qbank_state.json; do
  [ -e "$f" ] || continue
  EVENTS+=("$(basename "$(dirname "$f")")")
done

if [ "${#EVENTS[@]}" -eq 0 ]; then
  echo "No event data yet — nothing to back up."
  exit 0
fi

# Snapshot the previously-committed state before overwriting, so the
# commit-message script has both "old" and "new" to diff.
OLD_SNAPSHOT="$(mktemp -d)"
trap 'rm -rf "$OLD_SNAPSHOT"' EXIT
for slug in "${EVENTS[@]}"; do
  if [ -f "$DATABANK_DIR/$slug/.qbank_state.json" ]; then
    mkdir -p "$OLD_SNAPSHOT/$slug"
    cp "$DATABANK_DIR/$slug/.qbank_state.json" "$OLD_SNAPSHOT/$slug/"
  fi
done

for slug in "${EVENTS[@]}"; do
  mkdir -p "$DATABANK_DIR/$slug"
  cp "$APP_DIR/$slug/.qbank_state.json" "$DATABANK_DIR/$slug/"
  [ -f "$APP_DIR/$slug/question_bank.md" ] && cp "$APP_DIR/$slug/question_bank.md" "$DATABANK_DIR/$slug/"
done
[ -f "$APP_DIR/events_custom.json" ] && cp "$APP_DIR/events_custom.json" "$DATABANK_DIR/"

cd "$DATABANK_DIR"
git add -A

if git diff --cached --quiet; then
  echo "No changes since last backup."
  exit 0
fi

set +e
MSG="$(python3 "$SCRIPT_DIR/qbank-commit-message.py" "$OLD_SNAPSHOT" "$DATABANK_DIR" "${EVENTS[@]}")"
STATUS=$?
set -e

if [ "$STATUS" -eq 2 ]; then
  MSG="Initial snapshot: ${EVENTS[*]}"
elif [ "$STATUS" -eq 1 ] || [ -z "$MSG" ]; then
  MSG="Snapshot $(date -Is)"
fi

git commit -q -m "$MSG"
git push -q origin main 2>&1 | grep -v "^Enumerating\|^Counting\|^Compressing\|^Writing" || true
echo "Committed: $MSG"
