#!/usr/bin/env bash
# Root-only: change one managed instance's gunicorn --threads count via a
# systemd drop-in override, then reload+restart so it takes effect.
#
# Deliberately does NOT touch instances.conf. That file lives under deploy/,
# which _apply-update.sh's CODE_PATHS allow-list syncs (with --delete) from
# the git-tracked source on every "Update from GitHub" run — a value stored
# there would silently revert to whatever's committed in the repo the next
# time anyone updates. A systemd drop-in at /etc/systemd/system/<svc>.d/
# lives entirely outside any instance's app_dir, so _apply-update.sh's
# rsync never touches it; it survives every future update untouched. The
# *current* value is read back live via `systemctl show <svc>
# --property=ExecStart --value` (see admin_app.py's instance_resource_config),
# never cached in a file that could drift from what's actually running.
#
# --workers is NOT a parameter here, on purpose — see qbank.service's header
# comment for why raising it above 1 needs a lock redesign first
# (build_question_bank.py's per-event state lock AND jobs.py's background-
# job queue are both in-process, single-worker-process designs today). This
# script hardcodes --workers 1, so it is structurally incapable of producing
# anything else, independent of whatever the admin-app UI does or doesn't
# validate.
#
#   qbank-set-threads.sh <instance-name> <threads 1-64>
#
# Install: sudo cp deploy/qbank-set-threads.sh /usr/local/sbin/qbank-set-threads.sh
#          sudo chown root:root /usr/local/sbin/qbank-set-threads.sh
#          sudo chmod 750 /usr/local/sbin/qbank-set-threads.sh
# Sudoers: qbank-admin ALL=(root) NOPASSWD: /usr/local/sbin/qbank-set-threads.sh

set -euo pipefail

SRC="/opt/qbank-src"
LOG="/var/log/qbank-deploy.log"
INSTANCES_CONF="$SRC/deploy/instances.conf"
GUNICORN="/opt/qbank/venv/bin/gunicorn"

log() { echo "$(date -Is) $*" >> "$LOG"; }
die() { log "SET-THREADS REJECTED: $*"; echo "$*" >&2; exit 1; }

INSTANCE_NAME="${1:-}"
THREADS="${2:-}"
[ -n "$INSTANCE_NAME" ] && [ -n "$THREADS" ] || die "usage: qbank-set-threads.sh <instance-name> <threads>"

# Threads must be a bare positive integer in a sane range — guards against a
# typo (or a bug upstream) turning this into an unbounded-argument injection
# point or a resource-exhaustion footgun (e.g. "--threads 999999").
case "$THREADS" in
  ''|*[!0-9]*) die "threads must be a positive integer: $THREADS" ;;
esac
[ "$THREADS" -ge 1 ] && [ "$THREADS" -le 64 ] || die "threads must be between 1 and 64: $THREADS"

svc="" port=""
while IFS=: read -r name label cdir csvc cuser cport; do
  [[ "$name" == \#* ]] && continue
  [ -z "$name" ] && continue
  if [ "$name" = "$INSTANCE_NAME" ]; then
    svc="$csvc"; port="$cport"
  fi
done < "$INSTANCES_CONF"
[ -n "$svc" ] || die "unknown instance: $INSTANCE_NAME"

DROPIN_DIR="/etc/systemd/system/${svc}.d"
mkdir -p "$DROPIN_DIR"
# ExecStart= empty first, then set — the standard systemd idiom for
# *overriding* a multi-value directive via a drop-in rather than appending
# a second command to run alongside the original.
cat > "$DROPIN_DIR/threads-override.conf" <<EOF
# Generated by qbank-set-threads.sh — do not edit by hand; re-run the
# script (or the admin-app "Threads" control) instead. Survives Update
# from GitHub, which only touches each instance's app_dir, never
# /etc/systemd/system/.
[Service]
ExecStart=
ExecStart=$GUNICORN --workers 1 --threads $THREADS --bind 127.0.0.1:$port --timeout 120 review_app:app
EOF

systemctl daemon-reload
systemctl restart "$svc"
sleep 2
if systemctl is-active --quiet "$svc"; then
  log "$INSTANCE_NAME: threads set to $THREADS, $svc OK"
  echo "$svc now running with --threads $THREADS."
else
  log "$INSTANCE_NAME: threads set to $THREADS, $svc FAILED to start, check: journalctl -u $svc"
  echo "$svc failed to start with --threads $THREADS — check journalctl -u $svc" >&2
  exit 1
fi
